language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
 - PACKAGE_VERSION=high

matrix:
  include:
    - php: 5.3.2
      env: PACKAGE_VERSION=low

before_script:
  # FIXME: remove require on jackalope/jackalope-transport
  # temporary fix until https://github.com/composer/composer/issues/2038 is implemented
  - sed '/jackalope\/jackalope-transport/d' composer.json >> tmp; mv tmp composer.json
  - composer selfupdate
  - if [[ "$PACKAGE_VERSION" == "high" ]]; then composer update --prefer-source; fi
  - if [[ "$PACKAGE_VERSION" == "low" ]]; then composer update --prefer-lowest --prefer-source; fi

script: phpunit -c tests/phpunit.xml.dist

notifications:
  irc: "irc.freenode.org#jackalope"
