language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

env:
 - PACKAGE_VERSION=high

sudo: false

matrix:
  include:
    - php: 5.6
      env: PACKAGE_VERSION=low

before_script:
  - composer selfupdate
  - composer remove jackalope/jackalope-transport --no-update
  - if [[ "$PACKAGE_VERSION" == "high" ]]; then composer update --prefer-source; fi
  - if [[ "$PACKAGE_VERSION" == "low" ]]; then composer update --prefer-lowest --prefer-source; fi

script: vendor/bin/simple-phpunit

notifications:
  irc: "irc.freenode.org#jackalope"
